import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from "@/components/ui/Navbar";
import { NavbarSimple } from "@/components/Material-tailwind-Nav";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ghana ocean literacy academy",
  description: "Generated by create next app",
  icons: {
    icon: '/FOLA4.png', // /public path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-950">
      <link rel="icon" href="/FOLA4.png" sizes="any" />
      <body className="bg-slate-950">
        {/* <Navbar/> */}
        <NavbarSimple/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
